#define WIFI_SSID "valen"
#define WIFI_PASSWORD "123456789"
#define DATABASE_URL "meow-matic-default-rtdb.firebaseio.com"
#define DATABASE_SECRET "m7zW2aaen9SS7uiSEdv82tcukyid7jKkmA4a6HmN"
#define MOTOR "/Motor"
